spring:
  application:
    name: admin-service
  cloud:
    config:
      uri: http://localhost:9020
      discovery:
        service-id: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9010/eureka/
server:
  port: 9000